# Generated by Django 4.1.7 on 2023-04-14 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
                ('thubnail', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='consomation',
        ),
        migrations.DeleteModel(
            name='Consomation',
        ),
        migrations.AddField(
            model_name='menu',
            name='produits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.product'),
        ),
    ]
