# Generated by Django 4.1.7 on 2023-04-15 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_product_remove_menu_consomation_delete_consomation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thubnail',
            new_name='thumbnail',
        ),
    ]
