# Generated by Django 4.1.7 on 2023-04-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Product',
            new_name='product',
        ),
    ]
