# Generated by Django 4.1.4 on 2023-04-19 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_cart_ordered_remove_cart_ordered_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurateur',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='restaurateur',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='restaurateur',
            name='resto_name',
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resto_name', models.CharField(max_length=100)),
                ('phone_resto', models.CharField(max_length=15)),
                ('mail_address', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('map_url', models.URLField(blank=True, null=True)),
                ('proprietaire', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app1.restaurateur')),
            ],
        ),
    ]
