# Generated by Django 4.1.4 on 2023-05-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='nbr_personnes',
            field=models.IntegerField(default=0.00010001000100010001),
            preserve_default=False,
        ),
    ]
