# Generated by Django 4.1.4 on 2023-05-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_reservation_nbr_personnes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
