# Generated by Django 4.1.7 on 2023-05-17 00:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0010_order_delivery_order_delivery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_delivery',
            new_name='Livraison',
        ),
    ]
