# Generated by Django 4.1.7 on 2023-05-17 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_order_delivery_livraison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='order',
        ),
        migrations.AddField(
            model_name='livraison',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.cart'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livraison',
            name='heure',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
