# Generated by Django 4.1.7 on 2023-05-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_livraison_cart_livraison_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='order',
        ),
        migrations.AddField(
            model_name='livraison',
            name='order',
            field=models.ManyToManyField(to='app1.order'),
        ),
    ]
